# Generated by Django 5.2.13 on 2026-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_zone_auditlog_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('sales_team_lead', 'Sales Team Lead'), ('service_team_lead', 'Service Team Lead'), ('sales_team_member', 'Sales Team Member'), ('service_team_member', 'Service Team Member'), ('sales', 'Sales Team'), ('service', 'Service Team'), ('expert', 'Expert'), ('branch_manager', 'Branch Manager'), ('general_manager', 'General Manager'), ('site_engineer', 'Site Engineer')], default='farmer', max_length=20),
        ),
    ]
