# Generated by Django 5.2.13 on 2026-04-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expert_tags',
            field=models.CharField(blank=True, help_text='Comma-separated expert skills/tags (used for expert allocation and discovery).', max_length=255),
        ),
    ]
