# Generated by Django 5.2.13 on 2026-04-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='e.g., Rice, Wheat, Corn, Potato', max_length=100)),
                ('season', models.CharField(help_text='e.g., Winter 2026, Monsoon 2026', max_length=100)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('harvested', 'Harvested'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('planted_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crop_tracks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Rajshahi Mango Garden', max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('soil_type', models.CharField(blank=True, help_text='Auto-filled by soil classifier', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'land_parcels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Seedling, Vegetative, Flowering', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('tasks_json', models.JSONField(blank=True, default=list, help_text='List of tasks for this stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='lms_farming.croptrack')),
            ],
            options={
                'db_table': 'crop_stages',
                'ordering': ['created_at'],
            },
        ),
    ]
