# Generated by Django 5.2.13 on 2026-04-15 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms_farming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='croptrack',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_tracks', to='lms_farming.landparcel'),
        ),
    ]
