# Generated by Django 5.2.13 on 2026-04-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_farming', '0003_landparcelhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropTrackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('current_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='lms_farming.croptrack')),
            ],
            options={
                'db_table': 'crop_track_history',
                'ordering': ['-created_at'],
            },
        ),
    ]