# Generated by Django 5.2.8 on 2026-04-29 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_farming', '0005_cropactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Monsoon 2026, Winter 2026', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateField()),
                ('expected_end_at', models.DateField(blank=True, null=True)),
                ('actual_end_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('soil_preparation_notes', models.TextField(blank=True)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield in kg', max_digits=12, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield in kg', max_digits=12, null=True)),
                ('total_investment', models.DecimalField(blank=True, decimal_places=2, help_text='Total investment in BDT', max_digits=12, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total revenue in BDT', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farming_cycles', to='lms_farming.landparcel')),
            ],
            options={
                'db_table': 'farming_cycles',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmingCycleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('completed', 'Completed')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('current_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='lms_farming.farmingcycle')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farming_cycle_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farming_cycle_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cycle', '-created_at'], name='farming_cyc_cycle_i_305c38_idx')],
            },
        ),
    ]
