# Generated by Django 5.2.15 on 2026-06-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_farming", "0006_add_farming_cycle_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="landparcel",
            name="default_crop_type",
            field=models.CharField(
                blank=True, help_text="Default crop grown on this land", max_length=100
            ),
        ),
    ]
