# Generated by Django 5.2.15 on 2026-06-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_farming", "0007_landparcel_default_crop_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="landparcel",
            name="default_disease",
            field=models.CharField(
                blank=True, help_text="Auto-filled by disease detector", max_length=100
            ),
        ),
    ]
