# Generated by Django 5.2.15 on 2026-06-10 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_farming", "0008_landparcel_default_disease"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="croptrack",
            name="crop_name",
            field=models.CharField(
                blank=True, help_text="Legacy string field", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="landparcel",
            name="default_crop_type",
            field=models.CharField(
                blank=True, help_text="Legacy string field", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="CropType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_from",
                        to="lms_farming.croptype",
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_crops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crop_types",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="croptrack",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="tracks",
                to="lms_farming.croptype",
            ),
        ),
        migrations.AddField(
            model_name="landparcel",
            name="default_crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_lands",
                to="lms_farming.croptype",
            ),
        ),
    ]
