# Generated by Django 5.2.15 on 2026-06-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_farming", "0009_alter_croptrack_crop_name_and_more"),
    ]

    operations = []
