# Generated by Django 5.2.15 on 2026-06-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_farming", "0010_migrate_crop_types"),
    ]

    operations = []
