# Generated by Django 5.2.15 on 2026-06-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_farming", "0011_remove_crop_strings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="croptype",
            options={"ordering": ["name_en"]},
        ),
        migrations.RenameField(
            model_name="croptype",
            old_name="name",
            new_name="name_en",
        ),
        migrations.RemoveField(
            model_name="croptrack",
            name="crop_name",
        ),
        migrations.RemoveField(
            model_name="landparcel",
            name="default_crop_type",
        ),
        migrations.AddField(
            model_name="croptype",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="True if published for farmers, False for internal testing",
            ),
        ),
        migrations.AddField(
            model_name="croptype",
            name="name_bn",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
