# Generated by Django 5.2.13 on 2026-04-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('lms_farming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='land_parcel',
            field=models.ForeignKey(blank=True, help_text='Optional: link session to a specific land for context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='lms_farming.landparcel'),
        ),
    ]
