# Generated by Django 5.2.13 on 2026-04-15 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0002_initial'),
        ('lms_farming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.chatsession'),
        ),
        migrations.AddField(
            model_name='diseasedetectionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soilclassificationlog',
            name='land_parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms_farming.landparcel'),
        ),
        migrations.AddField(
            model_name='soilclassificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_classifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
