# Generated by Django 5.2.13 on 2026-04-28 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=20, unique=True)),
                ('gemini_api_key', models.TextField(blank=True, help_text='Stored Gemini API key used by the AI assistant.')),
                ('gemini_model', models.CharField(blank=True, max_length=120)),
                ('gemini_secondary_model', models.CharField(blank=True, max_length=120)),
                ('gemini_tertiary_model', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_service_configuration',
            },
        ),
        migrations.CreateModel(
            name='AIModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('disease_detection', 'Disease Detection'), ('soil_classification', 'Soil Classification')], max_length=32)),
                ('crop_type', models.CharField(blank=True, max_length=50, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('model_file', models.FileField(upload_to='ai_models/')),
                ('indices_file', models.FileField(blank=True, null=True, upload_to='ai_models/')),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_model_artifacts',
                'ordering': ['operation', 'crop_type', '-is_active', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('operation', 'crop_type'), name='unique_active_ai_model_per_scope')],
            },
        ),
    ]
