# Generated by Django 5.2.8 on 2026-04-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0008_add_crop_and_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
