# Generated by Django 5.2.13 on 2026-04-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0010_ai_model_usage_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aimodelusagehistory',
            new_name='ai_model_us_service_aac214_idx',
            old_name='ai_model_u_service_7b5c4a_idx',
        ),
        migrations.RenameIndex(
            model_name='aimodelusagehistory',
            new_name='ai_model_us_operati_5c6ea7_idx',
            old_name='ai_model_u_operat_3c0c6c_idx',
        ),
        migrations.RenameIndex(
            model_name='aimodelusagehistory',
            new_name='ai_model_us_user_ro_3d2634_idx',
            old_name='ai_model_u_user_ro_2e5f1d_idx',
        ),
    ]
