# Generated by Django 5.2.15 on 2026-06-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_engine",
            "0011_rename_ai_model_u_service_7b5c4a_idx_ai_model_us_service_aac214_idx_and_more",
        ),
        ("lms_farming", "0006_add_farming_cycle_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasedetectionlog",
            name="image_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diseasedetectionlog",
            name="land_parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lms_farming.landparcel",
            ),
        ),
        migrations.AddField(
            model_name="diseasedetectionlog",
            name="prediction_feedback",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correct", "Yes"),
                    ("incorrect", "No"),
                    ("not_sure", "Not Sure"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="soilclassificationlog",
            name="image_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="soilclassificationlog",
            name="prediction_feedback",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correct", "Yes"),
                    ("incorrect", "No"),
                    ("not_sure", "Not Sure"),
                ],
                max_length=20,
            ),
        ),
    ]
