# Generated by Django 5.2.15 on 2026-06-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0012_diseasedetectionlog_image_taken_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelartifact",
            name="parsed_classes",
            field=models.JSONField(
                blank=True,
                help_text="Auto-populated mapping of class indices to labels",
                null=True,
            ),
        ),
    ]
