# Generated by Django 5.2.15 on 2026-06-10 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0013_aimodelartifact_parsed_classes"),
        (
            "lms_farming",
            "0012_alter_croptype_options_rename_name_croptype_name_en_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Crop",
        ),
        migrations.AlterModelOptions(
            name="aimodelartifact",
            options={"ordering": ["operation", "crop", "-is_active", "-updated_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="aimodelartifact",
            name="unique_active_ai_model_per_scope",
        ),
        migrations.RemoveField(
            model_name="aimodelartifact",
            name="crop_type",
        ),
        migrations.AddField(
            model_name="aimodelartifact",
            name="crop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_models",
                to="lms_farming.croptype",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodelartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("operation", "crop"),
                name="unique_active_ai_model_per_scope",
            ),
        ),
    ]
