# Generated by Django 5.2.13 on 2026-04-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_assistant_daily_limit',
            field=models.PositiveIntegerField(default=0, help_text='Daily AI assistant messages'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='disease_detection_limit',
            field=models.PositiveIntegerField(default=0, help_text='Monthly disease detection scans'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='expert_appointment_limit',
            field=models.PositiveIntegerField(default=0, help_text='Monthly expert appointments'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='farming_suggestion_limit',
            field=models.PositiveIntegerField(default=0, help_text='Monthly smart farming suggestions'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='market_prediction_limit',
            field=models.PositiveIntegerField(default=0, help_text='Monthly market analysis requests'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='offline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('addon', 'Add-On')], default='primary', max_length=20),
        ),
    ]
